app/profilepage/page.tsx
=> created profilepage

app/components/Header.tsx
This pull request includes significant updates to the `Header` component to enhance the dropdown functionality and UI. The changes involve adding new hooks, restructuring the dropdown data, and updating the dropdown rendering logic for better user experience.
* Added `useRef` and `useEffect` hooks to manage dropdown references and handle clicks outside the dropdown to close it. (`app/components/Header.tsx`)
* Introduced a detailed `dropdownData` object to manage dropdown content dynamically, including categories, items, and images for mens, womens, and accessories sections. (`app/components/Header.tsx`)
* Updated the dropdown rendering logic to display categories and items in a grid layout with images and a "Shop All" link for each section. This includes separate handling for mens, …
=> Implement enhancements to the category list page

app/(admin)/productlist/page.tsx, app/components/AdminProductCard.tsx, app/components/TopBar.tsx
one componets is AdminProductCard and another one is TopBar for admin pages
=> added productlist page with two components

app/api/customer/products/route.tsx, app/api/customer/wishlist/route.tsx, app/api/products/[id]/route.tsx, app/api/search/route.tsx, app/api/suggestions/route.tsx, app/cart/page.tsx, app/components/DebugDisplay.tsx, app/components/Header.tsx, app/components/ProductCard.tsx, app/components/ProductCarousel.tsx, app/components/ProductDetailsSection.tsx, app/components/ProductImageGallery.tsx, app/components/ProductInformation.tsx, app/components/UserReviewsSection.tsx, app/context/CartContext.tsx, app/context/WishlistContext.tsx, app/hooks/useOnClickOutside.ts, app/layout.tsx, app/page.tsx, app/product/[id]/page.tsx, app/providers.tsx, app/search/page.tsx, app/wishlist/page.tsx, package-lock.json, package.json
This pull request introduces several new API routes and updates to existing ones to improve the functionality of the customer-facing product features. It includes connecting to MongoDB using Mongoose, handling various HTTP methods, and formatting product data for client-side consumption. Additionally, there are updates to the cart page and a new debug component.
* [`app/api/customer/products/route.tsx`](diffhunk://#diff-cc61a5eb76b64425c7b6b8e2b8f24826b128355e1dd4912cef364fcdffa00194R1-R58): Added a `GET` method to fetch products for customers, connecting to MongoDB and transforming the product data to a customer-friendly format.
* [`app/api/customer/wishlist/route.tsx`](diffhunk://#diff-c622c72d8fe0bb6aca10c3f21d678d47f2afbf16ef2e92037b0960c66729babaR1-R65): Added a `GET` method to fetch …
=> Cutomer backend

app/(admin)/inventorydetails/page.tsx, app/(admin)/inventoryedit/page.tsx, app/(admin)/inventorylist/page.tsx, app/api/inventory/[id]/route.tsx, app/api/inventory/route.tsx, app/api/products/route.tsx, app/api/seed-inventory/route.tsx
This pull request includes significant updates to the `InventoryDetailsPage` component to enhance functionality and improve code structure. The key changes include the introduction of dynamic data fetching, improved UI state management, and updates to the display logic for inventory details.
* **Dynamic Data Fetching and State Management:**
* Added `useEffect` to fetch inventory data from the API based on the provided inventory ID and manage loading and error states.
* Introduced state variables for `inventory`, `loading`, `error`, `selectedSize`, `selectedColor`, and `productColors`.
* **UI Updates:**
* Updated the top bar to include dynamic product images and placeholders if fewer than four color images are available.
* Added loading and error states to display appropriate messages and …
=> Inventory finetune

app/(admin)/discountcreate/page.tsx, app/(admin)/discountedit/page.tsx, app/(admin)/discountlist/page.tsx, app/(admin)/discountview/page.tsx, app/api/discounts/product/[productId]/route.tsx, app/api/discounts/route.tsx, app/components/ProductCard.tsx, models/Discount.tsx
This pull request includes significant updates to the discount creation and listing pages in the admin panel. The changes aim to enhance the user experience by adding new functionalities and improving the existing ones.
* **Enhanced Product and Category Selection**:
- Added search functionality for products, allowing users to filter and select products more efficiently.
- Introduced a new interface for selecting categories, displaying category images and titles.
* **Automatic Discount Status Calculation**:
- Removed manual discount status selection and implemented automatic status calculation based on start and end dates.
* **Price Breakdown Display**:
- Added a feature to display the original price, discounted price, and the amount saved for single product discounts.
* **Improved …
=> Discount finetune

app/components/Header.tsx
This pull request includes changes to the `Header` component in `app/components/Header.tsx` to improve the validation and display of the wishlist count. The most important changes include adding a new function to validate the wishlist items and updating the component to use this function.
Improvements to wishlist validation:
* Added `getValidWishlistCount` function to filter out null, undefined, or invalid items from the wishlist and return the count of valid items.
Updates to wishlist display:
* Updated the wishlist link to use `getValidWishlistCount` for displaying the count of valid wishlist items instead of the raw `wishlist.length`.
=> Add wishlist validation to count valid items in Header component

app/api/customer/products/route.tsx, app/api/customer/trending/route.tsx, app/components/ProductCard.tsx, app/page.tsx
This pull request includes significant updates to the product fetching and display logic, focusing on improving the handling of inventory status and categories, as well as enhancing the user interface for product tags and category toggles.
* [`app/api/customer/products/route.tsx`](diffhunk://#diff-cc61a5eb76b64425c7b6b8e2b8f24826b128355e1dd4912cef364fcdffa00194R4): Added logic to filter products based on inventory status and category, ensuring only in-stock products are fetched and displayed. [[1]](diffhunk://#diff-cc61a5eb76b64425c7b6b8e2b8f24826b128355e1dd4912cef364fcdffa00194R4) [[2]](diffhunk://#diff-cc61a5eb76b64425c7b6b8e2b8f24826b128355e1dd4912cef364fcdffa00194L29-R65)
* [`app/api/customer/trending/route.tsx`](diffhunk://#diff-9db8ed2ece9f690afe070dae0caa15bdb79043494046e8f57cbde0b2 …
=> Product casoroul

app/components/Header.tsx, app/components/HeaderPlaceholder.tsx, app/components/ProductCarousel.tsx, app/globals.css, app/page.tsx
This pull request includes significant updates to the `Header`, `HeaderPlaceholder`, `ProductCarousel`, and `HomePage` components to improve the user interface and user experience. The changes focus on enhancing scroll behavior, updating the product carousel's functionality, and refining the homepage layout.
* [`app/components/Header.tsx`](diffhunk://#diff-c241ab181629f79a98e7a2e3f1ad045d98962d4c6324c52ddee12578d11bfdaeR49-R86): Added new state variables and scroll event handling to show/hide the header based on scroll position.
* [`app/components/Header.tsx`](diffhunk://#diff-c241ab181629f79a98e7a2e3f1ad045d98962d4c6324c52ddee12578d11bfdaeL211-R242): Updated header styles to transition between fixed and relative positioning based on scroll position.
* …
=> Home page style

app/(admin)/couponcreate/page.tsx, app/(admin)/couponedit/page.tsx, app/(admin)/couponlist/page.tsx, app/(admin)/couponview/page.tsx, app/api/coupons/[id]/route.tsx, app/api/coupons/id/route.tsx, app/api/coupons/product/route.tsx, app/api/coupons/route.tsx, models/coupons.js, models/coupons.tsx
This pull request includes significant changes to the `CouponCreate` and `CouponEdit` components in the admin section of the application. The changes focus on enhancing form handling, adding error and loading states, and improving the user interface for creating and editing coupons.
Enhancements to `CouponCreate`:
* Added `useRouter` from `next/navigation` to handle navigation after form submission and cancellation.
* Introduced loading and error states to manage form submission feedback and display error messages. [[1]](diffhunk://#diff-8e93c52867ac82fbbb3441e0b9412c228abf4fa6bbd3f227d5d6f5d73d611895R4-R98) [[2]](diffhunk://#diff-8e93c52867ac82fbbb3441e0b9412c228abf4fa6bbd3f227d5d6f5d73d611895R135-R140)
* Updated form fields to include new properties such as `price`, `discount`, and …
=> Implement CRUD operations for coupons and integrate with admin pages

app/admin/productedit/[id]/page.tsx
This pull request includes several changes to the `ProductEdit` component in `app/admin/productedit/[id]/page.tsx` to improve type safety and consistency. The most important changes are the introduction of the `ProductFormData` interface and the use of specific types for various state variables and function parameters.
Improvements to type safety and consistency:
* Added `ProductFormData` interface to define the structure of the form data, and updated the `formData` state to use this type. ([app/admin/productedit/[id]/page.tsxR27-R50](diffhunk://#diff-c87052a7137d0abfe3555a00aae949e45d509a3b7f691ee094ad6c494a0939a4R27-R50))
* Changed the type of `mainProductImage` state to `string | ArrayBuffer | null` for better type safety. ([app/admin/productedit/[id]/page.tsxL54-R72](diffhunk://#diff-c …
=> refactor: enhance type safety in ProductEdit component

app/api/search/keywords/route.tsx, app/components/Header.tsx, app/hooks/useSearchHistory.ts, app/search/page.tsx
This pull request introduces a new keyword suggestion feature for the search functionality and integrates search history management. The primary changes include adding keyword suggestions, handling search history, and updating the `Header` component to support these new features.
* [`app/api/search/keywords/route.tsx`](diffhunk://#diff-7770e1a92d25deb03a66ab21ed56d052de048f0d60a432bf33c7acc2a5e72b60R1-R114): Added a new API route to fetch keyword suggestions based on search queries. This includes connecting to MongoDB, querying the `Product` collection, and extracting keywords from product data.
* [`app/components/Header.tsx`](diffhunk://#diff-c241ab181629f79a98e7a2e3f1ad045d98962d4c6324c52ddee12578d11bfdaeR52-R53): Integrated search history management by adding new state variables and …
=> Improvise search bar

app/(admin)/orderlist/page.tsx, app/api/checkout/route.tsx, app/api/orders/route.tsx
but still not categorized orders paid or .....
=> admin can view orders now on

app/components/Header.tsx
This pull request includes several improvements to the dropdown functionality in the `Header` component within the `app/components/Header.tsx` file. The changes focus on enhancing user experience by making the dropdowns more responsive and ensuring they close appropriately under various conditions.
Key changes include:
**Dropdown Responsiveness and Closing Behavior:**
* Added logic to close all dropdowns when scrolling (`setOpenDropdown`, `setShowDropdown`, `setActiveCategory`, `setShowUserDropdown`).
* Reduced the timeout duration for closing dropdowns on mouse leave from 200ms to 100ms to improve responsiveness.
* Modified the event listener to use `mousedown` instead of `click` for better responsiveness and ensured it closes all dropdowns when clicking outside.
* Added a dedicated …
=> Improve dropdown behavior and responsiveness in Header component

app/components/Footer.tsx, app/components/Header.tsx, app/components/ProductCard.tsx, app/components/ProductCarousel.tsx, app/page.tsx
Reverts Anuradha-Herath/Pinnacle#142
=> Revert "Product cards"

app/components/Footer.tsx, app/components/Header.tsx, app/components/ProductCard.tsx, app/components/ProductCarousel.tsx, app/page.tsx
Reverts Anuradha-Herath/Pinnacle#143
=> Revert "Revert "Product cards""

app/(user)/product/[id]/page.tsx, app/(user)/productReview/[id]/page.tsx, app/(user)/productReview/page.tsx, app/api/chatbot/route.tsx, app/api/products/route.tsx, app/components/Chatbot.tsx, app/components/ProductCard.tsx, app/components/UserReviewsSection.tsx, app/globals.css, app/layout.tsx, app/page.tsx, app/providers.tsx, lib/notificationService.ts
This pull request introduces several enhancements and refactorings across multiple components, focusing on improving user experience, code maintainability, and functionality. Key updates include redesigning skeleton loaders, refining chatbot animations, improving product recommendation logic, and fixing import paths.
* Redesigned the skeleton loader for the product detail page with a two-column layout, custom pulse animations, and more detailed placeholders for product gallery and information (`app/(user)/product/[id]/page.tsx`). ([app/(user)/product/[id]/page.tsxL350-R407](diffhunk://#diff-5a29afa4df37240e9a7622e2acf55af86b9bd934b7323f9d317037bcb9540143L350-R407))
* Updated the user reviews section to include a more visually appealing skeleton loader with custom animations and detailed …
=> Carousel changes;

app/api/discounts/route.tsx
=> changing the status of the discount from active to inactive when it is expired

app/(user)/checkout/page.tsx, app/api/orders/route.tsx, app/components/checkout/Cancel.tsx, app/components/checkout/Success.tsx
also created Cancel and Success components for checkout page
=> small changes on checkout page, order route

app/admin/orderlist/page.tsx, app/components/admin/TopBar.tsx
also small changes made in orderlistpage
=> made TopBar component for admin
